import { BudgetItem } from '../types/budget';
import { supabase } from './supabaseClient';

const STORAGE_KEY = 'berkeley_budget_data';

function parseAmount(value: string): number {
  if (!value || value.trim() === '') return 0;

  const cleanValue = value.replace(/[$,]/g, '');
  const parsed = parseFloat(cleanValue);
  return isNaN(parsed) ? 0 : parsed;
}

// IDs are generated by the database (gen_random_uuid())

export async function importBudgetData(): Promise<BudgetItem[]> {
  try {
    const fileUrl = new URL('../data/FY26 Budget - Sheet2.csv', import.meta.url);
    const response = await fetch(fileUrl.href);
    const csvText = await response.text();

    const lines = csvText.split('\n');
    const budgetItems: Omit<BudgetItem, 'id' | 'created_at' | 'updated_at'>[] = [];

    console.log('Total CSV lines:', lines.length);

    for (let i = 1; i < lines.length; i++) {
      const line = lines[i].trim();
      if (!line) continue;

      // Split by comma, but respect quoted fields
      const fields: string[] = [];
      let currentField = '';
      let inQuotes = false;
      
      for (let j = 0; j < line.length; j++) {
        const char = line[j];
        
        if (char === '"') {
          inQuotes = !inQuotes;
        } else if (char === ',' && !inQuotes) {
          fields.push(currentField.trim());
          currentField = '';
        } else {
          currentField += char;
        }
      }
      fields.push(currentField.trim());

      // Clean the fields
      const cleanField = (field: string) => {
        if (!field) return '';
        return field.replace(/^"|"$/g, '').replace(/""/g, '"').trim();
      };

      const cleanedFields = fields.map(cleanField);
      
      // Ensure we have at least 8 fields (pad with empty strings if needed)
      while (cleanedFields.length < 8) {
        cleanedFields.push('');
      }

      const [orgCode, fund, objectCode, description, fy2023, fy2024, fy2025, fy2026] = cleanedFields;

      if (!description) continue;

      budgetItems.push({
        org_code: orgCode || '',
        fund: fund || '',
        object_code: objectCode || '',
        description: description,
        fy2023_budget: parseAmount(fy2023),
        fy2024_budget: parseAmount(fy2024),
        fy2025_budget: parseAmount(fy2025),
        fy2026_budget: parseAmount(fy2026)
      });
    }

    // Insert into Supabase (chunked to be safe)
    const chunkSize = 500;
    for (let i = 0; i < budgetItems.length; i += chunkSize) {
      const chunk = budgetItems.slice(i, i + chunkSize);
      const { error } = await supabase.from('budget_items').insert(chunk);
      if (error) {
        console.error('Supabase insert error (budget_items):', error);
        break;
      }
    }

    // Store in localStorage as a fallback cache
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(budgetItems));
    } catch {}
    if (import.meta.env.DEV) {
      console.log(`✅ Successfully imported ${budgetItems.length} budget items`);
    }
    
    // Return normalized objects with minimal fields (id will be missing here)
    return (budgetItems as unknown) as BudgetItem[];
  } catch (error) {
    console.error('Error importing data:', error);
    throw error;
  }
}

export async function checkDataExists(): Promise<boolean> {
  // Prefer DB check
  const { count, error } = await supabase
    .from('budget_items')
    .select('id', { count: 'exact', head: true });
  if (!error && typeof count === 'number') {
    return count > 0;
  }
  const stored = localStorage.getItem(STORAGE_KEY);
  return stored !== null && stored !== '';
}

export async function getBudgetData(): Promise<BudgetItem[]> {
  // Try DB first
  const { data, error } = await supabase
    .from('budget_items')
    .select('id, org_code, fund, object_code, description, fy2023_budget, fy2024_budget, fy2025_budget, fy2026_budget, created_at, updated_at');
  if (!error && data) {
    return data as BudgetItem[];
  }

  // Fallback to local cache
  const stored = localStorage.getItem(STORAGE_KEY);
  if (!stored) return [];
  try {
    return JSON.parse(stored);
  } catch (e) {
    console.error('Error parsing stored data:', e);
    return [];
  }
}
